// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsFormsApp1;
//
//    var diak = Diak.FromJson(jsonString);

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Diak
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("TeljesNev")]
        public string TeljesNev { get; set; }
        public string ImageUrl
        {
            get
            {
                return $"https://randomuser.me/api/portraits/men/{Id}.jpg";
            }
        }

        override public string ToString()
        {
            return TeljesNev;
        }
    }

    public partial class Diak
    {
        public static List<Diak> FromJson(string json) => JsonConvert.DeserializeObject<List<Diak>>(json, WindowsFormsApp1.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Diak> self) => JsonConvert.SerializeObject(self, WindowsFormsApp1.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
